In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")


In [19]:
class perceptron:
    def __init__(self,eta:float =None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta=eta
        self.epochs=epochs
        
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias= np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias : \n{X_with_bias}")
         

In [20]:
obj= perceptron(eta=0.01,epochs=10)

In [21]:
obj.eta

0.01

In [22]:
obj.epochs

10

In [23]:
obj.weights

array([ 1.12325888e-04,  1.11846388e-04, -4.98267073e-05])

In [11]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [12]:
X=np.ones((4,2))

In [13]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.c_[X,-np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [16]:
y = np.ones((4,1))

In [17]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [24]:
obj.fit(X,y)

X with bias : 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
